# Generated by Django 5.0.3 on 2024-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_category_table_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'ordering': ('ordering',), 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
